# Generated by Django 3.2 on 2023-02-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('SP', 'Special'), ('BQ', 'Bouquet'), ('IP', 'Indoor Plants')], max_length=2, null=True),
        ),
    ]
