# Generated by Django 3.2 on 2023-01-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('FL', 'Special'), ('BQ', 'Bouquet'), ('IP', 'Indoor Plants')], max_length=2, null=True),
        ),
    ]
